### ISSUE TITLE
README error

### ISSUE THREAD

**Issue by deedoubledub** [craftfrancis/gitStati#3]
From your README:

> Method 2: Cloning
> 1. Create an empty directory to hold our files, or settle to place them in an existing directory if you wish.
> 2. Use the command git init in order to initialize this directory as a git directory. This will allow you to clone our directory in the next step.
> 3. Clone our repository by using this command: git clone https://github.com/craftfrancis/gitStati/
> 4. You will now find a directory containing all of our code in your specified directory

It is not necessary to create an empty git repo to clone git repos. Step 2 doesn't accomplish anything unless you want nested git repos for some reason.

**Comment by meansa** [comment]
Thanks- the issue's been taken care of!
