### ISSUE TITLE
Java Compilation Error

### ISSUE THREAD

**Issue by burdetp** [craftfrancis/gitStati#7]
# I'm trying to compile the code and receive the following error.

 $ javac gitStati.java 
gitStati.java:78: incompatible types
found   : java.lang.String
required: int
                switch (choice) {
                        ^
gitStati.java:107: incompatible types
found   : java.lang.String
required: int
                        switch (statusOption) {
                                ^
#2 errors

I'm running java version "1.6.0_65" on OS X 10.10.5.

**Comment by ghost** [comment]
Thank you for letting us know about this!

The compilation of Strings as the values in our Switch Case statements progressed without error on our machines, so it's very possible this might be a problem between Java versions. However, we've edited the code in a very simple manner that should solve this issue, regardless of the version somebody might have.

Hopefully, this solves your issue! Let us know what the result is so we can either continue working on it or close the issue.

**Comment by burdetp** [comment]
Thanks for the fast response. The fix you submitted resolved my problem.
